config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :posts
      resources :visits

      root to: "users#index"
  end
  
  # get 'posts/create'
  # get 'users/show'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  root to: 'home#index'
  resources :users, only: [:show]
  resources :posts, only: [:create]
  
  namespace :api, { format: 'json' } do
    resources :users, :only => [:show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DiaLogBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--<#%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>-->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-dark bg-dark d-flex justify-content-end">
        <div class="flex-grow-1 text-white p-2">DiaLogBook</div>
        
        <% if user_signed_in? %>
          <div class="btn btn-success">
            <%= link_to 'ホーム', user_path(current_user.id), class: 'text-white' %>
          </div>
          
          <!--<div class="text-white">-->
          <!--  <#%= current_user.fullname %>-->
          <!--</div>-->
          
          <% if @user.role == 'teacher' %>
            <div class="btn btn-secondary ms-2">
              <%= link_to '管理画面へ', admin_root_path, class: 'text-white' %>
            </div>
          <% end %>
          
          <div class="btn btn-danger ms-2">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'text-white' %>
          </div>
        <% else %>
          <div class="btn btn-primary ms-2">
            <%= link_to 'ログイン', new_user_session_path, class: 'text-white' %>
          </div>
          
          <div class="btn btn-success ms-2">
            <%= link_to '新規登録', new_user_registration_path, class: 'text-white' %>
          </div>
        <% end %>
      </nav>
    </header>
    
    <% if notice %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          <!--<span aria-hidden="true">&times;</span>-->
        </button>
      </div>
    <% end %>
    
    <% if alert %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          <!--<span aria-hidden="true">&times;</span>-->
        </button>
      </div>
    <% end %>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>